services:
    db:
        # M1 processor require platform
        platform: linux/x86_64
        # image: mysql:latest
        build: ./mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_HOST=mysql
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ../db:/var/lib/mysql
            - ../logs/mysql:/var/log/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "127.0.0.1:8080:80"
    api:
        build: ./api
        container_name: api
        restart: always
        volumes:
            - ./api/:/app
            - ../logs/api/:/logs
        environment:
            - FLASK_APP=/src/run.py
            - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
            - DEBUG=1
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - OPENAI_MODEL=gpt-5-mini
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - MYSQL_HOST=db
            - API_LOG_FILE=/logs/api.log
        expose:
            - 9000

    ui:
        build: ./ui
        container_name: ui
        restart: always
        expose:
            - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        volumes:
            - ../logs/nginx:/var/log/nginx/
        ports:
            - "8000:80"