FROM mysql:latest

# Set the locale
# RUN apt-get update && apt-get install -y locales
# RUN microdnf install -y glibc-langpack-en
# RUN locale-gen en_US.UTF-8
# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8